[package]
name = "ssql"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
arrow2 = "0.14.2"
bytes = "1.2.1"
prost = "0.11.0"
prost-types = "0.11.0"

[build-dependencies]
prost-build = "*"
